"""Evaluation and greedy decoding for the parallel auxiliary Transformer."""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

import torch
from torch import Tensor

from agimaze_predict.data.prepared import PreparedExample

from .model import AuxTransformer, target_cross_entropy
from .reporting import GreedyPrediction, write_greedy_error_log
from .tokenizer import collate_aux_examples, serialize_aux_example


@torch.no_grad()
def greedy_target_bytes(model: AuxTransformer, prefix: Sequence[int], *, target_bytes: int) -> bytes:
    """Autoregressively decode literal target bytes after a source prefix.

    Target length comes from the known evaluation label. The auxiliary stream
    remains fixed to this source prefix for every generated target byte, so no
    generated target byte can flow back into auxiliary cross-attention.
    """

    if not prefix:
        raise ValueError("prefix must contain at least one token")
    if len(prefix) + target_bytes - 1 > model.config.context_length:
        raise ValueError("prefix plus target exceeds model context length")

    model.eval()
    generated = list(prefix)
    for _ in range(target_bytes):
        input_ids = torch.tensor([generated], dtype=torch.long, device=next(model.parameters()).device)
        aux_lengths = torch.tensor([len(prefix)], dtype=torch.long, device=input_ids.device)
        next_byte = int(model(input_ids, aux_lengths=aux_lengths)[0, -1].argmax().item())
        if next_byte > 255:
            # PAD is not a valid generated byte. It is retained in the vocabulary
            # only for batch padding; mapping it to NUL makes the failure explicit.
            next_byte = 0
        generated.append(next_byte)
    return bytes(generated[len(prefix) :])


@torch.no_grad()
def evaluate_examples(
    model: AuxTransformer,
    examples: Sequence[PreparedExample],
    *,
    device: torch.device,
    batch_size: int = 64,
    greedy_error_log: str | Path | None = None,
) -> dict[str, float]:
    """Compute target-byte NLL and non-teacher-forced exact POS-span accuracy."""

    if not examples:
        raise ValueError("cannot evaluate an empty example collection")

    model.eval()
    total_loss = 0.0
    total_target_bytes = 0
    greedy_exact = 0
    predictions: list[GreedyPrediction] = []
    diagnostics_total: dict[str, float] = {}
    diagnostics_batches = 0

    for start in range(0, len(examples), batch_size):
        batch_examples = examples[start : start + batch_size]
        batch = collate_aux_examples(batch_examples, context_length=model.config.context_length)
        input_ids = torch.tensor(batch["input_ids"], dtype=torch.long, device=device)
        labels = torch.tensor(batch["labels"], dtype=torch.long, device=device)
        aux_lengths = torch.tensor(batch["aux_lengths"], dtype=torch.long, device=device)
        logits, diagnostics = model(
            input_ids,
            aux_lengths=aux_lengths,
            return_aux_diagnostics=True,
        )
        for key, value in diagnostics.items():
            diagnostics_total[key] = diagnostics_total.get(key, 0.0) + value
        diagnostics_batches += 1
        active = labels.ne(-100)
        target_bytes = int(active.sum().item())
        loss = target_cross_entropy(logits, labels)
        total_loss += float(loss.item()) * target_bytes
        total_target_bytes += target_bytes

        for example in batch_examples:
            item = serialize_aux_example(example)
            prefix = item.token_ids[: item.target_start]
            expected = bytes(item.token_ids[item.target_start :])
            predicted = greedy_target_bytes(model, prefix, target_bytes=len(expected))
            greedy_exact += int(predicted == expected)
            if greedy_error_log is not None:
                predictions.append(GreedyPrediction(example=example, predicted=predicted))

    metrics = {
        "target_byte_nll": total_loss / total_target_bytes,
        "greedy_exact_target_accuracy": greedy_exact / len(examples),
    }
    # The direct causal usage check: turn off only main<-aux residuals,
    # keeping the main model and source serialization unchanged.
    ablated_loss = 0.0
    for start in range(0, len(examples), batch_size):
        batch_examples = examples[start : start + batch_size]
        batch = collate_aux_examples(batch_examples, context_length=model.config.context_length)
        input_ids = torch.tensor(batch["input_ids"], dtype=torch.long, device=device)
        labels = torch.tensor(batch["labels"], dtype=torch.long, device=device)
        aux_lengths = torch.tensor(batch["aux_lengths"], dtype=torch.long, device=device)
        logits = model(input_ids, aux_lengths=aux_lengths, disable_aux=True)
        active_bytes = int(labels.ne(-100).sum().item())
        ablated_loss += float(target_cross_entropy(logits, labels).item()) * active_bytes
    metrics["aux_ablation_delta_target_byte_nll"] = ablated_loss / total_target_bytes - metrics[
        "target_byte_nll"
    ]
    metrics.update({key: value / diagnostics_batches for key, value in diagnostics_total.items()})
    if greedy_error_log is not None:
        metrics["greedy_error_count"] = float(write_greedy_error_log(greedy_error_log, predictions))
    return metrics
