"""Evaluation and greedy decoding for the vanilla byte-Transformer baseline."""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

import torch
from torch import Tensor

from agimaze_predict.data.prepared import PreparedExample

from .model import ByteTransformer, target_cross_entropy
from .reporting import GreedyPrediction, write_greedy_error_log
from .tokenizer import collate_byte_examples, serialize_example


@torch.no_grad()
def greedy_target_bytes(model: ByteTransformer, prefix: Sequence[int], *, target_bytes: int) -> bytes:
    """Autoregressively decode after a byte/state-token prefix.

    Target length comes from the known evaluation label. This avoids conflating
    the first smoke-test's transition metric with a separate EOS-generation
    problem. State-token slots, when enabled, are deterministic input positions;
    only generated literal bytes are returned and compared to the POS span.
    """

    if not prefix:
        raise ValueError("prefix must contain at least one token")
    if len(prefix) + target_bytes - 1 > model.config.context_length:
        raise ValueError("prefix plus target exceeds model context length")

    model.eval()
    generated = list(prefix)
    for _ in range(target_bytes):
        input_ids = torch.tensor([generated], dtype=torch.long, device=next(model.parameters()).device)
        next_byte = int(model(input_ids)[0, -1].argmax().item())
        if next_byte > 255:
            # PAD is not a valid generated byte. It is retained in the vocabulary
            # only for batch padding; mapping it to NUL makes the failure explicit.
            next_byte = 0
        generated.append(next_byte)
    return bytes(generated[len(prefix) :])


@torch.no_grad()
def evaluate_examples(
    model: ByteTransformer,
    examples: Sequence[PreparedExample],
    *,
    device: torch.device,
    batch_size: int = 64,
    greedy_error_log: str | Path | None = None,
) -> dict[str, float]:
    """Compute target-byte NLL and non-teacher-forced exact POS-span accuracy."""

    if not examples:
        raise ValueError("cannot evaluate an empty example collection")

    model.eval()
    total_loss = 0.0
    total_target_bytes = 0
    greedy_exact = 0
    predictions: list[GreedyPrediction] = []

    for start in range(0, len(examples), batch_size):
        batch_examples = examples[start : start + batch_size]
        batch = collate_byte_examples(
            batch_examples,
            context_length=model.config.context_length,
            state_tokens=model.config.state_tokens,
        )
        input_ids = torch.tensor(batch["input_ids"], dtype=torch.long, device=device)
        labels = torch.tensor(batch["labels"], dtype=torch.long, device=device)
        logits = model(input_ids)
        active = labels.ne(-100)
        target_bytes = int(active.sum().item())
        loss = target_cross_entropy(logits, labels)
        total_loss += float(loss.item()) * target_bytes
        total_target_bytes += target_bytes

        for example in batch_examples:
            item = serialize_example(example, state_tokens=model.config.state_tokens)
            prefix = item.token_ids[: item.target_start]
            expected = bytes(item.token_ids[item.target_start :])
            predicted = greedy_target_bytes(model, prefix, target_bytes=len(expected))
            greedy_exact += int(predicted == expected)
            if greedy_error_log is not None:
                predictions.append(GreedyPrediction(example=example, predicted=predicted))

    metrics = {
        "target_byte_nll": total_loss / total_target_bytes,
        "greedy_exact_target_accuracy": greedy_exact / len(examples),
    }
    if greedy_error_log is not None:
        metrics["greedy_error_count"] = float(write_greedy_error_log(greedy_error_log, predictions))
    return metrics
